import { useState } from "react";
import { Button, Empty, ErrorText, Modal, Section } from "../../components/ui";
import { useWorkspace } from "../../hooks/useWorkspace";
import { batch } from "../../services/platform";
import { EmailHistory } from "./Emails";
import type { ScheduleException } from "./types";
export function CourseSchedule({courseId}:{courseId:string}) {
  const {data,edit,navigate,refresh}=useWorkspace();
  const [removing,setRemoving]=useState<ScheduleException|null>(null),[error,setError]=useState("");
  const rows=(data.scheduleExceptions ?? []).filter(e=>e.course_id===courseId).sort((a,b)=>b.date.localeCompare(a.date));
  return <><Section title="Weekly meetings" action={<Button onClick={()=>edit({kind:'course',id:courseId})}>Edit weekly schedule</Button>}>{data.schedules.filter(s=>s.course_id===courseId).map(s=><p key={s.id}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][s.day_of_week]} · {s.start_time}–{s.end_time}</p>)}<p className="helper">Weekly meetings stay intact when you apply a change to one date.</p></Section><Section title="Class exceptions">{!rows.length && <Empty title="No class exceptions" description="Approved cancellations, room changes, and reschedules appear here."/>}{rows.map(e=><article key={e.id} className="email-proposal"><h3>{e.date} · {e.exception_type}</h3><p>Original: {e.original_start_time}–{e.original_end_time}</p>{e.exception_type!=='Cancelled' && <p>Meeting: {e.new_date || e.date} · {e.new_start_time || e.original_start_time}–{e.new_end_time || e.original_end_time} · {e.room || data.courses.find(c=>c.id===courseId)?.room}</p>}<p className="muted">{e.reason}</p><div className="email-actions">{e.source_email_id && <Button onClick={()=>navigate(`email/${encodeURIComponent(e.source_email_id!)}`)}>Source email</Button>}<Button onClick={()=>setRemoving(e)}>Restore original meeting…</Button></div><EmailHistory kind="schedule" id={e.id}/></article>)}</Section><ErrorText error={error}/>
    {removing && <Modal title="Restore original meeting?" onClose={()=>setRemoving(null)}><div className="modal-body"><p>Remove this exception for {removing.date}, {removing.original_start_time}? The weekly timetable will apply again. The change history will remain.</p></div><div className="modal-footer"><Button onClick={()=>setRemoving(null)}>Cancel</Button><Button variant="primary" onClick={async()=>{try{await batch([{sql:"DELETE FROM course_schedule_exceptions WHERE id=?",params:[removing.id],expectChanges:1},{sql:"INSERT INTO academic_change_log(id,entity_type,entity_id,field_name,old_value,new_value,source_type,source_sender,source_subject,source_received_at) VALUES(?,'course',?,'schedule exception',?,'Original meeting restored','Manual','','Manual restoration',?)",params:[crypto.randomUUID(),courseId,JSON.stringify(removing),new Date().toISOString()]}]);await refresh();setRemoving(null);}catch(e){setError((e as Error).message);}}}>Restore meeting</Button></div></Modal>}
  </>;
}
