// Generate portable table descriptors and transactional capture from migrations 1–16.
// Review this allowlist whenever the academic schema changes.
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
const tables = `semesters courses course_schedules exams assignments tasks calendar_events files attachments course_schedule_exceptions academic_change_log
lectures readings grade_categories grade_items previous_exam_attempts exam_topics course_topics
study_sessions study_blocks lecture_files grading_scales previous_exam_questions professors course_professors
degree_programs degree_groups degree_requirements degree_options degree_courses degree_allocations
degree_plans degree_prerequisites local_import_sources local_import_records degree_import_snapshots
course_syllabus course_syllabus_policy course_syllabus_material course_syllabus_office_hours`.split(/\s+/);
const db = new DatabaseSync(':memory:');
for (const file of fs.readdirSync('src/db').filter(f => /^(00[1-9]|01[0-6])_.*\.sql$/.test(f)).sort()) db.exec(fs.readFileSync(`src/db/${file}`, 'utf8'));
const localFields = new Set(['storage_directory','folder_path','absolute_path','relative_path','source_path','accessed_at','missing','last_seen_at']);
const schemas = {};
let sql = `-- Generated by scripts/sync-schema.mjs. Do not edit capture triggers by hand.
CREATE TABLE sync_context (id INTEGER PRIMARY KEY CHECK(id=1), device_id TEXT NOT NULL, clock INTEGER NOT NULL DEFAULT 0, applying INTEGER NOT NULL DEFAULT 0, cursor INTEGER NOT NULL DEFAULT 0);
INSERT INTO sync_context(id,device_id) VALUES(1,lower(hex(randomblob(16))));
CREATE TABLE sync_outbox (table_name TEXT NOT NULL, record_key TEXT NOT NULL, seq INTEGER NOT NULL, payload TEXT, PRIMARY KEY(table_name,record_key));
CREATE TABLE sync_versions (table_name TEXT NOT NULL, record_key TEXT NOT NULL, version INTEGER NOT NULL, PRIMARY KEY(table_name,record_key));
CREATE TABLE sync_conflicts (table_name TEXT NOT NULL, record_key TEXT NOT NULL, local_payload TEXT, remote_payload TEXT, remote_version INTEGER NOT NULL, PRIMARY KEY(table_name,record_key));
CREATE TABLE sync_blobs (file_id TEXT PRIMARY KEY, hash TEXT NOT NULL, local_signature TEXT NOT NULL DEFAULT '');
CREATE TABLE sync_preferences (key TEXT PRIMARY KEY, value TEXT NOT NULL);
`;
for (const table of tables) {
  const info = db.prepare(`PRAGMA table_info("${table}")`).all();
  const foreign = db.prepare(`PRAGMA foreign_key_list("${table}")`).all();
  const local = info.filter(c => localFields.has(c.name) || foreign.some(f => f.from === c.name && !tables.includes(f.table))).map(c => c.name);
  const columns = info.filter(c => !local.includes(c.name)).map(c => c.name);
  const keys = info.filter(c => c.pk).sort((a,b)=>a.pk-b.pk).map(c=>c.name);
  schemas[table] = { columns, keys, local, foreign: foreign.filter(f=>tables.includes(f.table)).map(f=>({column:f.from,table:f.table,to:f.to})) };
  const key = prefix => `json_array(${keys.map(k=>`${prefix}."${k}"`).join(',')})`;
  const payload = prefix => `json_object(${columns.flatMap(c=>[`'${c}'`,`${prefix}."${c}"`]).join(',')})`;
  for (const action of ['INSERT','UPDATE','DELETE']) {
    const prefix = action === 'DELETE' ? 'OLD' : 'NEW';
    const when = action === 'UPDATE' ? ` AND (${columns.map(c=>`OLD."${c}" IS NOT NEW."${c}"`).join(' OR ')})` : '';
    sql += `CREATE TRIGGER sync_${table}_${action.toLowerCase()} AFTER ${action} ON "${table}" WHEN (SELECT applying FROM sync_context WHERE id=1)=0${when} BEGIN
UPDATE sync_context SET clock=clock+1 WHERE id=1;
INSERT INTO sync_outbox(table_name,record_key,seq,payload) VALUES('${table}',${key(prefix)},(SELECT clock FROM sync_context WHERE id=1),${action==='DELETE'?'NULL':payload(prefix)}) ON CONFLICT(table_name,record_key) DO UPDATE SET seq=excluded.seq,payload=excluded.payload;
END;
`;
  }
  // Upgrade capture includes existing academic content; no user data is rewritten.
  sql += `INSERT INTO sync_outbox SELECT '${table}',${key('r')},0,${payload('r')} FROM "${table}" r;\n`;
}
fs.mkdirSync('src/features/sync', {recursive:true});
fs.writeFileSync('src/features/sync/schema.json', JSON.stringify(schemas, null, 2)+'\n');
fs.writeFileSync('src/db/017_device_sync.sql', sql);
// Migration 18 adds the deliberately small portable preference allowlist.
const cloudSchemas={...schemas,synced_preferences:{columns:['id','value'],keys:['id'],local:[],foreign:[]}};
fs.mkdirSync('supabase/migrations',{recursive:true});
fs.writeFileSync('supabase/migrations/202609110002_entity_schema.sql',Object.entries(cloudSchemas).map(([entity,descriptor])=>`INSERT INTO public.unidesk_entity_schema(entity,descriptor) VALUES('${entity}','${JSON.stringify(descriptor).replaceAll("'","''")}'::jsonb);`).join('\n')+'\n');
db.close();
